"""Add shap columnn

Revision ID: 05b2a9bb6c3e
Revises: 87f463aa5112
Create Date: 2022-10-19 23:22:32.059090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b2a9bb6c3e'
down_revision = '87f463aa5112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding_tensor', sa.Column('data_reduced', sa.JSON(), nullable=True))
    op.add_column('record_label_association', sa.Column('shap', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record_label_association', 'shap')
    op.drop_column('embedding_tensor', 'data_reduced')
    # ### end Alembic commands ###
